version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.10.4
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=starmon_network
      - --entrypoints.web.address=:80
      - --accesslog.filepath=/logs/access.log
      - --accesslog.bufferingsize=100
      - --log.level=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/traefik/logs:/logs:rw
    labels:
      - 'traefik.enable=true'
      - traefik.docker.network=starmon_network
    # Join to existing network : tsatnet
    networks:
      starmon_network:
    # Restart policy : unless-stopped
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    deploy:
      mode: replicated
      replicas: 4
    restart: always
    networks:
      - starmon_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.starmon-api.rule=(Host(`localhost`) || Host(`starmon1.telkomsat.co.id`)) && PathPrefix(`/api`)
      - traefik.http.routers.starmon-api.priority=20
      - traefik.http.middlewares.starmon-api-strip.stripprefix.prefixes=/api
      - "traefik.http.routers.starmon-api.middlewares=starmon-api-strip@docker" 
      - traefik.http.services.starmon-api.loadbalancer.server.port=8000
  
  dashboard:
    container_name: star-dashboard
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    restart: always
    networks:
      - starmon_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=(Host(`localhost`) || Host(`starmon1.telkomsat.co.id`)) && Pathprefix(`/`)
      - traefik.http.routers.dashboard.priority=10
      - traefik.http.services.dashboard.loadbalancer.server.port=80
 
networks:
  starmon_network:
    external: true