version: "3"

services:
  web:
    container_name: star-dashboard
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - app_network

networks:
  app_network:
    external: true