@host = http://localhost:8000
@user = nettocyber
@password = telkomsat


### Authentication -  Login
# @name login
POST {{host}}/auth/login
content-type : application/json

{
  "username": "{{user}}",
  "password": "{{password}}"
}


### POST Change Password
# @name change-password
POST {{host}}/auth/change-password
content-type : application/json
Authorization: Bearer {{access_token}}

{
  "uuid" : "f9544a2b-981f-4bb7-b451-218fa7c23c13",
  "oldPassword" : "telkomsat",
  "newPassword" : "T3lkomsat"
}

### Get token
@access_token = {{login.response.body.data.accessToken}}

### Authentication -  Login
POST http://localhost/api/auth/login
content-type : application/json

{
  "username": "user",
  "password": "telkomsat"
}



      
### Get Telemetry
GET http://localhost:8000/telemetry?start=1688662800000&end=1688673600000&serviceLineNumber=AST-1642430-93633-42


### Get Service Line
GET http://localhost:8000/service-line/AST-1642430-93633-42

### GET Uptime
GET http://localhost:8000/service-line/uptime/AST-1642430-93633-42

### GET Customer
GET http://localhost:8000/customer/f9544a2b-981f-4bb7-b451-218fa7c23c13
Authorization: Bearer {{access_token}}




### Get Customer From Another App
GET http://localhost:8000/customer/f9544a2b-981f-4bb7-b451-218fa7c23c13
Authorization: Secret b451b04e19fb7596c860d03ca015447827897de9583536db72943a41f96db924

### GET Customer
GET http://localhost:8000/customer/8cc0cdb8-2760-4a6c-9175-bc0b0e581fbd


### GET Raw Data
GET http://localhost:8000/telemetry/raw-data?serviceLine=AST-1642430-93633-42&month=7&year=2023
