### root
GET http://localhost:8000

### Authentication -  Login
POST http://localhost:8000/auth/login
content-type : application/json

{
  "username": "user",
  "password": "telkomsat"
}
      
### Get
GET http://localhost:8000/telemetry?start=1688662800000&end=1688673600000&serviceLineNumber=AST-1642430-93633-42


### Get
GET http://localhost:8000/service-line/AST-1642430-93633-42